### ISSUE TITLE
[Suggestion] "Minting on a Raspberry Pi"

### ISSUE THREAD

**Issue by Lamz0rNewb** [NuNetwork/documentation#22]
**Page Title**: Minting on a Raspberry Pi
**URL**: https://docs.nubits.com//nu-raspberry-minting/
### Installing BerkeleyDB4.8 from source - in case no repository with compiled packages can be found

> don't install libdb++-dev from repository - it might be newer than 4.8 and nud compiled with libdb > 4.8 converts .dat files in ~/.nu to a format that is not compatible with official releases that use libdb4.8  

**Adjusted dependencies for compiling nud with libdb4.8:**

`sudo apt-get install checkinstall subversion git git-core build-essential libssl-dev libboost-dev libboost-system-dev libboost-filesystem-dev libboost-program-options-dev libboost-thread-dev libcurl4-openssl-dev libminiupnpc-dev`

`cd ~/`
`wget http://download.oracle.com/berkeley-db/db-4.8.30.tar.gz`
`tar xvf db-4.8.30.tar.gz`
`cd ~/db-4.8.30/build_unix`
`../dist/configure --enable-cxx`
`make`

> this might take a while - even on RaPi2  

`sudo make install`
`export BDB_INCLUDE_PATH="/usr/local/BerkeleyDB.4.8/include"`
`export BDB_LIB_PATH="/usr/local/BerkeleyDB.4.8/lib"`
`sudo ln -s /usr/local/BerkeleyDB.4.8/lib/libdb-4.8.so /usr/lib/libdb-4.8.so`
`sudo ln -s /usr/local/BerkeleyDB.4.8/lib/libdb_cxx-4.8.so /usr/lib/libdb_cxx-4.8.so`

**Comment by CoinGame** [comment]
Have you run through the steps that you outlined here?

**Comment by Lamz0rNewb** [comment]
Yes, but you can try yourself if you want to verify it ;)
Maybe it's necessary to underline that exporting the variables should be done close to compiling nud - I'm not sure whether the export survives a reboot or a change of context.
